'use strict';
const $=s=>document.querySelector(s);
let indexData,currentItem,current,frame=0,playing=false,raf=0,lastAdvance=0,filter='all';
const cache=new Map();
const colors={raw:'#b38b69',fixed:'#176c70',target:'#7960ad',truth:'#a0a8ae',ink:'#283c44',grid:'#d7e0e5'};
const labels={SCALE_NOT_VERIFIED:'尺度未经验证',CAMERA_NOT_VERIFIED:'相机运动未经验证',ILLUSTRATIVE_ROBOT_ALIGNMENT:'机器人对齐仅作示意',GRASP_CANDIDATE_ONLY:'抓取候选未验证接触',MIRROR_CONVENTION_UNKNOWN:'镜像约定未知',LICENSE_UNVERIFIED:'许可待核对',SYNTHETIC_TEST_FIXTURE:'合成测试，不算真实示教'};
const kinds={synthetic:'合成验证 · 有程序真值',human_video:'真实 RGB · 模型伪标注',rejected_robot_video:'来源拒绝 · 机器人视频'};
const links=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[0,17],[17,18],[18,19],[19,20]];
const finite=v=>typeof v==='number'&&Number.isFinite(v);
const pos=T=>T&&T[0]&&[T[0][3],T[1][3],T[2][3]].every(finite)?[T[0][3],T[1][3],T[2][3]]:null;
function canvas(id){const c=$(id),d=devicePixelRatio||1,r=c.getBoundingClientRect();c.width=Math.max(1,r.width*d);c.height=Math.max(1,r.height*d);const ctx=c.getContext('2d');ctx.scale(d,d);return {ctx,w:r.width,h:r.height};}
function path(ctx,points,color,width=2,dash=[]){ctx.beginPath();let start=true;for(const p of points){if(!p){start=true;continue;}if(start){ctx.moveTo(...p);start=false}else ctx.lineTo(...p);}ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.stroke();ctx.setLineDash([]);}
function dot(ctx,p,color,r=4){if(!p)return;ctx.beginPath();ctx.arc(...p,r,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}
function text(ctx,str,p,color=colors.ink){ctx.fillStyle=color;ctx.font='11px system-ui';ctx.fillText(str,...p);}
function selectList(){const items=indexData.items.filter(i=>filter==='all'||i.kind===filter);$('#case-count').textContent=items.length;const list=$('#case-list');list.replaceChildren();for(const i of items){const b=document.createElement('button');b.className='case-card'+(i.id===currentItem?.id?' active':'');b.dataset.kind=i.kind;b.setAttribute('aria-pressed',String(i.id===currentItem?.id));const name=document.createElement('span');name.className='name';name.textContent=i.title;const meta=document.createElement('span');meta.className='meta';const indicator=document.createElement('span');indicator.className='indicator';meta.append(indicator,document.createTextNode(i.kind==='synthetic'?'可复现的误差注入':i.kind==='human_video'?`${i.summary.observed_frames}/${i.summary.frames} 帧有三维估计`:'人工抽帧核查 · 排除'));b.append(name,meta);b.onclick=()=>select(i.id);list.append(b);}}
async function select(id){stop();currentItem=indexData.items.find(i=>i.id===id);const item=currentItem;current=null;frame=0;selectList();$('#case-title').textContent=item.title;$('#case-description').textContent=item.description;$('#kind').textContent=kinds[item.kind];$('#download').hidden=!item.data;if(item.data)$('#download').href=item.data;
const video=$('#source-video');video.pause();video.removeAttribute('src');video.load();video.hidden=!item.video;$('#human-scene').hidden=!!item.video;$('#overlay').hidden=!item.video;$('#no-robot').hidden=item.kind!=='rejected_robot_video';
$('#claim').className='notice'+(item.kind==='synthetic'?' synthetic':'');$('#claim').textContent=item.kind==='synthetic'?'本例是程序生成的压力测试。误差可与合成真值比较，不能用来报告真实视频三维准确率。':item.kind==='human_video'?'真实视频已运行手部模型；三维尺度与相机运动尚未验证。机器人回放采用显式标记的示意对齐，不进入真实机器人动作训练。':'这段素材来自 liuhanyu 的视频样例目录，但画面实际是机器人。已拒绝作为人类数据使用。';
$('#source-title').textContent=item.kind==='synthetic'?'01 人手导出的原始 / 修复目标':'01 原始 RGB 与检测关键点';$('#source-caption').textContent=item.kind==='human_video'?'21 点模型估计；遮挡不等于已恢复。任务描述来自上游 VLM。':item.kind==='synthetic'?'程序真值只用于验证，不进入真实数据统计。':'来源分类由本轮人工抽帧核查。';
if(item.video)video.src=item.video;
if(item.data){if(!cache.has(id)){const response=await fetch(item.data);if(!response.ok)throw Error(`样例读取失败 ${id}`);cache.set(id,await response.json());}if(currentItem.id!==id)return;current=cache.get(id);}
const s=item.summary;for(const [id,key] of [['m-observed','observed_frames'],['m-repair','repaired_frames'],['m-geometry','geometry_valid_frames'],['m-training','robot_training_frames']])$('#'+id).textContent=s[key]??'—';
$('#frame').max=Math.max(0,(current?.timestamp.length||70)-1);$('#frame').value=0;$('#quality-list').replaceChildren();for(const reason of current?.training_exclusion_reasons||['NOT_HUMAN_VIDEO']){const span=document.createElement('span');span.className='quality-item';span.textContent=labels[reason]||'不是人类视频';$('#quality-list').append(span);}draw();}
function projection(points,w,h){const iso=p=>[p[0]-.65*p[1],-.8*p[2]+.25*p[0]+.32*p[1]];const ps=points.filter(p=>p&&p.every(finite)).map(iso);if(!ps.length)ps.push([0,0],[.6,.4]);const xs=ps.map(p=>p[0]),ys=ps.map(p=>p[1]);let xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);const scale=Math.min((w-65)/Math.max(.15,xmax-xmin),(h-55)/Math.max(.15,ymax-ymin));return p=>{if(!p||!p.every(finite))return null;const a=iso(p);return [w/2+(a[0]-(xmin+xmax)/2)*scale,h/2+(a[1]-(ymin+ymax)/2)*scale]};}
function drawRobot(){const {ctx,w,h}=canvas('#robot-scene');ctx.clearRect(0,0,w,h);if(!current)return;const all=current.robot_link_points.flat().filter(p=>p?.every(finite));const targets=current.target_pose_robot.map(pos);const project=projection([...all,...targets],w,h);for(let i=0;i<=6;i++){const z=0;path(ctx,[[0,i*.1-.3,z],[.7,i*.1-.3,z]].map(project),colors.grid,1);path(ctx,[[i*.1,-.3,z],[i*.1,.3,z]].map(project),colors.grid,1);}path(ctx,targets.map(project),colors.target,1,[3,4]);const ls=current.robot_link_points[frame];if(ls&&ls.every(p=>p.every(finite))){path(ctx,ls.map(project),colors.fixed,5);ls.forEach(p=>dot(ctx,project(p),colors.fixed,3));}const target=project(pos(current.target_pose_robot[frame]));if(target){ctx.strokeStyle=colors.target;ctx.lineWidth=2;ctx.strokeRect(target[0]-5,target[1]-5,10,10);}const actual=project(pos(current.robot_actual_pose[frame]));dot(ctx,actual,colors.fixed,4);const T=current.target_pose_robot[frame],p=pos(T);if(p){for(let j=0;j<3;j++){const q=p.map((v,k)=>v+T[k][j]*.055);path(ctx,[project(p),project(q)],[colors.raw,colors.fixed,colors.target][j],2);}}text(ctx,'参考臂 · 6 DOF',[12,h-12],'#788b95');}
function drawHuman(){const {ctx,w,h}=canvas('#human-scene');ctx.clearRect(0,0,w,h);if(!current)return;const raw=current.raw_pose_world.map(pos),fixed=current.repaired_pose_world.map(pos),truth=current.truth_pose_world?.map(pos)||[];const proj=projection([...raw,...fixed,...truth],w,h);path(ctx,truth.map(proj),colors.truth,2,[3,4]);path(ctx,raw.map(proj),colors.raw,1.5);path(ctx,fixed.map(proj),colors.fixed,2.5);dot(ctx,proj(raw[frame]),colors.raw,5);dot(ctx,proj(fixed[frame]),colors.fixed,5);text(ctx,'原始估计',[12,20],colors.raw);text(ctx,'修复后',[85,20],colors.fixed);text(ctx,'独立合成真值',[145,20],colors.truth);const T=current.repaired_pose_world[frame],p=pos(T);if(p){const width=current.aperture_m[frame]||.04;const a=p.map((v,k)=>v-T[k][0]*width/2),b=p.map((v,k)=>v+T[k][0]*width/2);path(ctx,[proj(a),proj(b)],colors.target,4);dot(ctx,proj(a),colors.target,4);dot(ctx,proj(b),colors.target,4);}text(ctx,'短缺失带修复标志；长缺失保持断开',[12,h-12],'#788b95');}
function drawOverlay(){const {ctx,w,h}=canvas('#overlay');ctx.clearRect(0,0,w,h);if(!current?.keypoints)return;const points=current.keypoints[frame]?.landmarks_2d;if(!points)return;const video=$('#source-video'),vw=video.videoWidth||640,vh=video.videoHeight||360,scale=Math.min(w/vw,h/vh),ox=(w-vw*scale)/2,oy=(h-vh*scale)/2;const ps=points.map(p=>p&&p.every(finite)?[ox+p[0]*vw*scale,oy+p[1]*vh*scale]:null);for(const [a,b] of links)if(ps[a]&&ps[b])path(ctx,[ps[a],ps[b]],'#8de5d1',2);ps.forEach(p=>dot(ctx,p,'#fff2ae',2.5));}
function drawPlot(){const {ctx,w,h}=canvas('#trajectory');ctx.clearRect(0,0,w,h);if(!current){text(ctx,'来源被拒绝，没有生成轨迹。',[12,40]);return;}const t=current.timestamp,raw=current.raw_pose_world.map(pos).map(p=>p?p[1]*1000:null),fixed=current.repaired_pose_world.map(pos).map(p=>p?p[1]*1000:null),truth=current.truth_pose_world?.map(pos).map(p=>p?p[1]*1000:null)||[];const values=[...raw,...fixed,...truth].filter(finite);if(!values.length){text(ctx,'没有可用的三维姿态；保留原视频。',[12,40]);return;}let lo=Math.min(...values),hi=Math.max(...values);const pad=Math.max(5,(hi-lo)*.15);lo-=pad;hi+=pad;const x=i=>44+(w-56)*(t[i]-t[0])/Math.max(.1,t[t.length-1]-t[0]),y=v=>16+(h-45)*(hi-v)/(hi-lo);for(let k=0;k<3;k++){const v=lo+(hi-lo)*k/2;path(ctx,[[44,y(v)],[w-12,y(v)]],colors.grid,1);text(ctx,v.toFixed(0),[3,y(v)+4],'#788b95');}for(let i=0;i<t.length;i++){if(!current.human_valid[i]){ctx.fillStyle='#e2cbb33b';ctx.fillRect(x(i),16,Math.max(3,(w-56)/t.length),h-45);}}path(ctx,truth.map((v,i)=>finite(v)?[x(i),y(v)]:null),colors.truth,1,[3,3]);path(ctx,raw.map((v,i)=>finite(v)?[x(i),y(v)]:null),colors.raw,1.4);path(ctx,fixed.map((v,i)=>finite(v)?[x(i),y(v)]:null),colors.fixed,2);path(ctx,[[x(frame),14],[x(frame),h-29]],'#778690',1);text(ctx,t[0].toFixed(1)+' s',[44,h-8],'#788b95');text(ctx,t[t.length-1].toFixed(1)+' s',[w-44,h-8],'#788b95');}
function draw(){drawRobot();if(!$('#human-scene').hidden)drawHuman();if(!$('#overlay').hidden)drawOverlay();drawPlot();const t=current?.timestamp[frame]??frame/10;$('#time').textContent=`${t.toFixed(2)} s · ${frame}`;$('#frame').value=frame;if(!current){$('#frame-detail').textContent='来源分类不符合人类数据要求，未生成机器人动作。';$('#hand-status').textContent='已拒绝';$('#robot-status').textContent='未运行';return;}$('#hand-status').textContent=current.observed[frame]?'本帧有观测':current.human_valid[frame]?'本帧为插值':'本帧缺失';$('#robot-status').textContent=current.geometry_valid[frame]?'几何检查通过':'本帧未通过';const d=$('#frame-detail');d.replaceChildren();const e=current.ik_position_error_m[frame];const lines=[`观测：${current.observed[frame]?'模型有输出':'无可靠输出'} · 修复：${current.repair_mask[frame]?'是（离线）':'否'}`,`末端位置误差：${finite(e)?(e*1000).toFixed(2)+' mm':'不可计算'}`,`阶段：${current.phase[frame]} · 身份轨迹：${current.track_id[frame]}`,`真实机器人动作准入：${current.robot_training_valid[frame]?'通过':'未通过'}`];for(const line of lines){const p=document.createElement('p');p.textContent=line;d.append(p);}}
function stop(){playing=false;cancelAnimationFrame(raf);$('#source-video').pause();$('#play').textContent='播放';}
function tick(now){if(!playing)return;if(now-lastAdvance>100){lastAdvance=now;const n=current?.timestamp.length||70;frame=(frame+1)%n;const video=$('#source-video');if(currentItem.video&&video.readyState>=1)video.currentTime=current?.timestamp[frame]??frame/10;draw();}raf=requestAnimationFrame(tick);}
$('#play').onclick=()=>{if(playing)stop();else{playing=true;$('#play').textContent='暂停';lastAdvance=performance.now();raf=requestAnimationFrame(tick);}};
$('#frame').oninput=e=>{stop();frame=Number(e.target.value);const video=$('#source-video');if(currentItem?.video&&video.readyState>=1)video.currentTime=current?.timestamp[frame]??frame/10;draw();};
$('#source-video').addEventListener('loadedmetadata',drawOverlay);$('#source-video').addEventListener('seeked',drawOverlay);
for(const b of document.querySelectorAll('.filter'))b.onclick=()=>{filter=b.dataset.filter;for(const x of document.querySelectorAll('.filter')){x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));}selectList();const first=indexData.items.find(i=>filter==='all'||i.kind===filter);if(first&&filter!=='all'&&currentItem?.kind!==filter)select(first.id).catch(showError);};
new ResizeObserver(()=>{if(currentItem)draw();}).observe($('.review'));
function showError(error){$('#case-title').textContent='加载失败';$('#case-description').textContent=error.message;console.error(error);}
async function training(){
  try {
    const response=await fetch('data/training.json'); if(!response.ok)return;
    const r=await response.json(); $('#training-status').textContent=r.status||'训练记录';
    const target=$('#training-results'); target.replaceChildren();
    const intro=document.createElement('p'); intro.textContent=r.claim; target.append(intro);
    function table(title,headers,rows){
      const heading=document.createElement('h3'); heading.textContent=title; target.append(heading);
      const t=document.createElement('table'),head=document.createElement('tr');
      for(const h of headers){const cell=document.createElement('th');cell.textContent=h;head.append(cell);}t.append(head);
      for(const row of rows){const tr=document.createElement('tr');for(const value of row){const td=document.createElement('td');td.textContent=value??'—';tr.append(td);}t.append(tr);}target.append(t);
    }
    const f=v=>Number.isFinite(v)?v.toFixed(5):'—';
    if(r.runs?.length){table('人类预训练 · 小型 CNN / 单种子',
      ['条件','窗口 / 步数','初始 loss','最终 loss','样本曝光','平均梯度','参数变化 L2'],
      r.runs.map(x=>[x.condition,`${x.samples} / ${x.steps}`,f(x.initial_loss),f(x.final_loss),x.human_sample_exposures,f(x.encoder_gradient_mean),f(x.parameter_delta_l2)]));
      const n=document.createElement('p');n.textContent='不同目标的 loss 单位不同，不能横向比较大小。这里只是训练集诊断；隐式条件的运动探针头未经运动监督。';target.append(n);
    }
    if(r.robot_finetuning?.length){
      const runs=r.robot_finetuning;
      table('RoboTwin adjust_bottle · 8 段训练 / 2 段留出 · 每组 200 步',
        ['初始化','留出 MSE ↓','图片置乱 MSE','图片置零 MSE','闭环成功率'],
        [...runs.map(x=>[x.condition,f(x.final_validation_normalized_mse),f(x.shuffled_validation_image_mse),f(x.zero_validation_image_mse),'未测']),
        ['保持当前状态',f(runs[0].state_persistence_baseline_mse),'—','—','未测'],
        ['训练集动作均值',f(runs[0].constant_train_mean_baseline_mse),'—','—','未测']]);
      const warning=document.createElement('p'); warning.className='result-caveat';
      warning.textContent='这轮最关键的结果：保持当前关节状态的简单基线优于所有小模型。人类数据进入了优化，但尚未证明控制收益。下一步需动作序列目标、更多独立 episode、多种子和闭环评测；不能据此评出显式 / 隐式赢家或真机替代率。'; target.append(warning);
    }
    const link=document.createElement('a');link.href='data/training.json';link.textContent='查看完整训练指标与权重哈希 ↗';target.append(link);
  }catch(error){console.error('Training report',error);}
}
fetch('data/index.json').then(r=>{if(!r.ok)throw Error('请先运行 h2r gallery');return r.json();}).then(async r=>{indexData=r;const s=r.summary;$('#counts').innerHTML=`<div><strong>${s.real_human_clips}</strong>真实人类片段</div><div><strong>${s.synthetic_cases}</strong>合成压力测试</div><div><strong>${s.rejected_sources}</strong>来源拒绝</div>`;$('#generated-at').textContent='本次结果：'+new Date(r.created_at).toLocaleString('zh-CN');await select(r.items.find(i=>i.kind==='human_video')?.id||r.items[0].id);training();}).catch(showError);
